blog/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from blog import views

urlpatterns = patterns('',
    url(
            r'^$',
            views.index,
            name = 'index'
        ),
    url(
            r'^page/(?P<page>\d+)$',
            views.indexpage,
            name = 'indexpage'
        ),
    url(
            r'^tag/(?P<tag>[^/]+)$',
            views.taglist,
            name = 'taglist'
        ),
    url(
            r'^tag/(?P<tag>[^/]+)/page/(?P<page>\d+)$',
            views.tagpage,
            name = 'tagpage'
        ),
    url(
            r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/?$',
            views.datelist,
            name = 'datelist'
        ),
    url(
            r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/page/(?P<page>\d+)$',
            views.datepage,
            name = 'datepage'
        ),
    url(
            r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<slug>[^/]+)$',
            views.read,
            name = 'read'
        ),
    url(
            r'^code-chunk/(?P<language>[^/]+)/(?P<slug>[^/]+)$',
            views.codechunk,
            name = 'codechunk'
        ),
    url(
            r'^atom.xml$',
            views.feed,
            name = 'feed'
        ),
    url(
            r'^feed$',
            RedirectView.as_view(url=reverse_lazy('blog:feed'))
        ),
)

gergelypolonkaiweb/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.http import HttpResponse

admin.autodiscover()

handler404 = 'basics.views.notfound'
handler500 = 'basics.views.serverror'
handler403 = 'basics.views.forbidden'
handler400 = 'basics.views.badrequest'

urlpatterns = patterns('',
    url(
            r'^$',
            'blog.views.mainpage',
            name = 'home'
        ),
    url(
            r'^google150e54bda5f96d97',
            lambda r: HttpResponse("", mimetype="text/plain")
        ),
    url(
            r'^robots\.txt$',
            TemplateView.as_view(template_name = 'robots.txt', content_type = 'text/plain')
        ),
    url(
            r'^pinterest-26239.html$',
            TemplateView.as_view(template_name = 'pinterest-26239.html')
        ),
    url(
            r'^blog/',
            include(
                    'blog.urls',
                    namespace = 'blog'
                )
        ),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(
    #        r'^admin/doc/',
    #        include('django.contrib.admindocs.urls')
    #    ),
    url(
            r'^admin/',
            include(admin.site.urls)
        ),
    url(
            r'^',
            include(
                    'basics.urls',
                    namespace = 'basics'
                )
        ),
)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from taggit.managers import TaggableManager

class Post(models.Model):
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add = True)
    title = models.CharField(max_length = 100)
    slug = models.SlugField(editable = False, max_length = 100)
    content = models.TextField()
    draft = models.BooleanField()
    tags = TaggableManager()

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)

        super(Post, self).save(*args, **kwargs)

    def created_at_rss(self):
        return self.created_at.strftime('%a, %d %b %Y %T %z')

class CodeChunk(models.Model):
    language = models.CharField(max_length = 20)
    created_at = models.DateTimeField(auto_now_add = True)
    title = models.CharField(max_length = 100)
    slug = models.SlugField(editable = False, max_length = 100)
    description = models.TextField(blank = True)
    content = models.TextField()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)

        super(CodeChunk, self).save(*args, **kwargs)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.models import Post, CodeChunk
from django.core.urlresolvers import reverse
import datetime
import pytz
from django.templatetags.static import static

def mainpage(request):
    last_posts = Post.objects.filter(draft = False).order_by('-created_at')[:5]
    return render(request, 'blog/listing.html', {'posts': last_posts})

def listing(request, tag, year, month, day, page):
    kwargs = {}
    kwargs['draft'] = False

    view = 'index'

    if (tag == None):
        view = 'index'
    else:
        kwargs['tags__slug'] = tag
        view = 'tag'

    if (year != None):
        kwargs['created_at__year'] = year

        if (month != None):
            kwargs['created_at__month'] = month

            if (day != None):
                kwargs['created_at__day'] = day

    post_list = Post.objects.filter(**kwargs)
    paginator = Paginator(post_list.order_by('-created_at'), 10)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if paginator.num_pages > 1:
        view = view + 'page'

    return render(request, 'blog/listing.html', {
            'posts': posts,
            'tag': tag,
            'view': "blog:" + view
        })

def index(request):
    return listing(request, None, None, None, None, 1)

def indexpage(request, page):
    return listing(request, None, None, None, None, page)

def taglist(request, tag):
    return listing(request, tag, None, None, None, 1)

def tagpage(request, tag, page):
    return listing(request, tag, None, None, None, page)

def datelist(request, year, month, day):
    return listing(request, None, year, month, day, 1)

def datepage(request, year, month, day, page):
    return listing(request, None, year, month, day, page)

def read(request, year, month, day, slug):
    post = get_object_or_404(Post,
            created_at__year = int(year),
            created_at__month = int(month),
            created_at__day = int(day),
            slug = slug,
            draft = False
        )
    next_post = Post.objects.filter(created_at__gt = post.created_at, draft = False).order_by('created_at')[0:1]
    prev_post = Post.objects.filter(created_at__lt = post.created_at, draft = False).order_by('-created_at')[0:1]

    if not next_post:
        next_post = None
    else:
        next_post = next_post[0]

    if not prev_post:
        prev_post = None
    else:
        prev_post = prev_post[0]

    return render(request, 'blog/view.html', {
            'post': post,
            'prev_post': prev_post,
            'next_post': next_post,
        })

def codechunk(request, language, slug):
    chunk = get_object_or_404(CodeChunk, language = language, slug = slug)
    return render(request, 'blog/code-chunk.html', {'codechunk': chunk})

def feed(request):
    latest_post = Post.objects.filter(draft = False).order_by('-created_at')[0:1]

    if not latest_post:
        latest_date = datetime.datetime(1983, 3, 7, 11, 54, 45, 0, pytz.timezone('Europe/Budapest'))
    else:
        latest_date = latest_post[0].created_at

    posts = Post.objects.order_by('-created_at')[:10]

    return render(request, 'blog/feed.xml', {
                    'site_url': request.build_absolute_uri(reverse('home')),
                    'profile_pic': request.build_absolute_uri(static('images/profile.png')),
                    'last_build_date': latest_date.strftime('%a, %d %b %Y %T %z'),
                    'posts': posts,
                },
            content_type = 'application/xml'
        )

blog/templates/blog/code-chunk.html
{% extends 'front_base.html' %}

{% load code_chunks %}

{% block content %}
<div class="code-chunk">
    <p class="code-title">{{ codechunk.title }}</p>
    {{ codechunk.content|syhilite:codechunk.language }}
    {% if codechunk.description %}
    <div class="code-description">
        {{ codechunk.description|safe }}
    </div>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/listing.html
{% extends "front_base.html" %}

{% block content %}
{% if posts %}
{% include 'paginator.html' with list=posts %}
{% for post in posts %}
{% with title_links=True %}
{% include 'blog/post.html' %}
{% endwith %}
{% endfor %}
{% include 'paginator.html' with list=posts %}
{% else %}
<p>No posts are returned for your query.</p>
{% endif %}
{% endblock %}

blog/templates/blog/post.html
{% load code_chunks %}
{% load get_post_relative_link from blog_link %}
<div class="post">
    <h3>{% if title_links %}<a href="{% url 'blog:read' post.created_at.year post.created_at.month post.created_at.day post.slug %}">{% endif %}{{ post.title }}{% if title_links %}</a>{% else %}<div class="plusone-container"><div class="g-plusone" data-annotation="inline" data-size="small" data-width="300"></div></div>{% endif %}</h3>
    <p class="article-date">{{ post.created_at|date:'m-d-Y :: H:i' }} by {{ post.user.first_name }} {{ post.user.last_name }}</p>
    {{ post.content|insert_code_chunks }}
{% if post.tags.all %}
    <p class="article-tags">Tags:
{% for tag in post.tags.all %}
        <a href="{% url 'blog:taglist' tag.slug %}">{{ tag.name }}</a>
{% endfor %}
    </p>
{% endif %}
{% if not title_links %}
    <div class="g-plus" data-action="share" data-height="15"></div>
{% endif %}
</div>
{% if not title_links %}
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'gergelypolonkai';

    (function() {
        var dsq = document.createElement('script');
        dsq.type = 'text/javascript';
        dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
{% if prev_post %}
Previous: <a href="{% get_post_relative_link prev_post %}">{{ prev_post.title }}</a>
{% endif %}
{% if next_post %}
Next: <a href="{% get_post_relative_link next_post %}">{{ next_post.title }}</a>
{% endif %}
{% endif %}

blog/templates/blog/view.html
{% extends "front_base.html" %}

{% block content %}
{% include 'blog/post.html' %}
{% endblock %}