basics/urls.py
from django.conf.urls import patterns, url
from basics import views

urlpatterns = patterns('',
    url(r'^resume$',     views.resume,     name = 'resume'),
    url(r'^resume.pdf$', views.resumepdf,  name = 'resumepdf'),
    url(r'^about$',      views.about,      name = 'about'),
    url(r'^disclaimer$', views.disclaimer, name = 'disclaimer'),
)

blog/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from blog import views

urlpatterns = patterns('',
    url(
            r'^$',
            views.index,
            name = 'index'
        ),
    url(
            r'^page/(?P<page>\d+)$',
            views.indexpage,
            name = 'indexpage'
        ),
    url(
            r'^tag/(?P<tag>[^/]+)$',
            views.taglist,
            name = 'taglist'
        ),
    url(
            r'^tag/(?P<tag>[^/]+)/page/(?P<page>\d+)$',
            views.tagpage,
            name = 'tagpage'
        ),
    url(
            r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/?$',
            views.datelist,
            name = 'datelist'
        ),
    url(
            r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/page/(?P<page>\d+)$',
            views.datepage,
            name = 'datepage'
        ),
    url(
            r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<slug>[^/]+)$',
            views.read,
            name = 'read'
        ),
    url(
            r'^code-chunk/(?P<language>[^/]+)/(?P<slug>[^/]+)$',
            views.codechunk,
            name = 'codechunk'
        ),
    url(
            r'^atom.xml$',
            views.feed,
            name = 'feed'
        ),
    url(
            r'^feed$',
            RedirectView.as_view(url=reverse_lazy('blog:feed'))
        ),
)

gergelypolonkaiweb/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.http import HttpResponse

admin.autodiscover()

handler404 = 'basics.views.notfound'
handler500 = 'basics.views.serverror'
handler403 = 'basics.views.forbidden'
handler400 = 'basics.views.badrequest'

urlpatterns = patterns('',
    url(
            r'^$',
            'blog.views.mainpage',
            name = 'home'
        ),
    url(
            r'^google150e54bda5f96d97',
            lambda r: HttpResponse("", mimetype="text/plain")
        ),
    url(
            r'^robots\.txt$',
            TemplateView.as_view(template_name = 'robots.txt', content_type = 'text/plain')
        ),
    url(
            r'^pinterest-26239.html$',
            TemplateView.as_view(template_name = 'pinterest-26239.html')
        ),
    url(
            r'^blog/',
            include(
                    'blog.urls',
                    namespace = 'blog'
                )
        ),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(
    #        r'^admin/doc/',
    #        include('django.contrib.admindocs.urls')
    #    ),
    url(
            r'^admin/',
            include(admin.site.urls)
        ),
    url(
            r'^',
            include(
                    'basics.urls',
                    namespace = 'basics'
                )
        ),
)

gergelypolonkaiweb/templates/front_base.html
{% load static from staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Gergely Polonkai{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}" />
        {% compress css %}
        {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static "css/front.css" %}" media="screen" />
        <link rel="stylesheet" type="text/css" href="{% static "css/blog.css" %}" media="screen" />
        <link rel="stylesheet" type="text/css" href="{% static "css/resume.css" %}" media="screen" />
        <link rel="stylesheet" type="text/css" href="{% static "css/code.css" %}" media="screen" />
        {% endblock %}
        {% endcompress %}
        <link rel="alternate" type="application/rss+xml" title="Gergely Polonkai's Blog - RSS Feed" href="//{{ request.META.SERVER_NAME }}{% url 'blog:feed' %}" />
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    </head>
    <body>
        <div id="content-wrapper">
            <div id="header" style="background-image: url('{% static "images/header/"|add:header %}');">
                <div id="picture">
                    <img src="{% static "images/profile.png" %}" alt="" />
                </div>
                <h1><a href="{% url 'home' %}">Gergely Polonkai</a></h1>
                <h2>developer, systems engineer and administrator</h2>
                <div id="contact-list">
                    <a href="mailto:gergely@polonkai.eu" target="_blank"><img src="{% static "images/email_16.png" %}" alt="E-mail" /></a>
                    <a href="http://www.linkedin.com/in/gergelypolonkai" target="_blank"><img src="{% static "images/linkedin_16.png" %}" alt="LinkedIn profile" /></a>
                    <a href="skype:gergely.polonkai" target="_blank"><img src="{% static "images/skype_16.png" %}" alt="Skype" /></a>
                    <a href="http://facebook.com/Polesz" target="_blank"><img src="{% static "images/facebook_16.png" %}" alt="Facebook profile" /></a>
                    <a href="https://plus.google.com/+GergelyPolonkai/about" target="_blank"><img src="{% static "images/google_plus_16.png" %}" alt="Google+ profile" /></a>
                    <a href="gtalk:chat?jid=gergely@polonkai.eu" target="_blank"><img src="{% static "images/googletalk_16.png" %}" alt="Google Talk" /></a>
                    <a href="http://twitter.com/GergelyPolonkai" target="_blank"><img src="{% static "images/twitter_16.png" %}" alt="Twitter" /></a>
                    <a href="http://gergelypolonkai.tumblr.com" target="_blank"><img src="{% static "images/tumblr_16.png" %}" alt="Tumblr" /></a>
                    <a href="http://gergelypolonkai.deviantart.com" target="_blank"><img src="{% static "images/deviantart_16.png" %}" alt="deviantArt" /></a>
                    <a href="{% url 'blog:feed' %}"><img src="{% static "images/rss_16.png" %}" alt="RSS Feed" /></a>
                </div>
            </div>
            <div id="content-padding"></div>
            <div id="menu">
{% if tagcloud|length > 0 %}
                <div id="tagcloud-button"><img alt="" src="{% static "images/tagcloud.png" %}" /></div>
{% endif %}
                <ul>
                    <li {% if view_name|slice:"-7:" == ".resume" %} class="active"{% endif %}><a href="{% url 'basics:resume' %}">Resume</a></li>
                    <li {% if view_name|slice:":5" == "blog." %} class="active"{% endif %}><a href="{% url 'blog:index' %}">Blog</a></li>
                    <li {% if view_name|slice:"-6:" == ".about" %} class="active"{% endif %}><a href="{% url 'basics:about' %}">About me</a></li>
                </ul>
                <br class="clear" />
            </div>
{% if tagcloud|length > 0 %}
            <div id="tag-cloud">
{% for cloudItem in tagcloud %}
                <a href="{% url 'blog:taglist' cloudItem.slug %}" class="size{{ cloudItem.size }}">{{ cloudItem.name }}</a>{% if not loop.last %} | {% endif %}
{% endfor %}
            </div>
{% endif %}
            <div id="content">
{% block content %}{% endblock content %}
            </div>
        </div>
        <div id="bottombar-wrapper">
            <div id="bottombar-padding"></div>
            <div id="bottombar"{% if app.environment == 'dev' %} style="bottom: 40px;"{% endif %}>
                :: <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" /></a> Copyright &copy; 2012-2013, Gergely Polonkai :: <a href="{% url 'basics:disclaimer' %}">Disclaimer</a> ::
            </div>
        </div>
        <a href="https://github.com/gergelypolonkai" id="github-ribbon" target="_blank"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_orange_ff7600.png" alt="Fork me on GitHub"></a>
        <iframe src="http://githubbadge.appspot.com/badge/gergelypolonkai?s=1&a=0" style="border: 0; height: 142px; width: 200px; overflow: hidden; display: none; position: absolute; top: 100px; left: 100px;" frameBorder="0" id="github-badge"></iframe>
        <script type="text/javascript">
            $(document).ready(function() {
                $('.at-obfuscation').html('@');

                $('#tagcloud-button').click(function() {
                    $('#tag-cloud').toggle('slow');
                });

                $('#github-ribbon').mouseover(function() {
                    $('#github-badge').fadeIn();
                });

                $('#github-ribbon').mouseout(function() {
                    $('#github-badge').fadeOut();
                });

                $(document).mousemove(function(e) {
                    $('#github-badge').css({
                        top: e.pageY + 5,
                        left: e.pageX + 5
                    });
                });
            });

            (function() {
                var po = document.createElement('script');
                po.type = 'text/javascript';
                po.async = true;
                po.src = 'https://apis.google.com/js/client:plusone.js?onload=start';

                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(po, s);
            })();

            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-43569023-1', 'polonkai.eu');
            ga('send', 'pageview');
        </script>
    </body>
</html>

gergelypolonkaiweb/templates/paginator.html
{% if list.paginator.num_pages > 1 %}
    <div class="paginator">
        {% if list.number > 1 %}
            {% if tag %}
            <a href="{% url view page=1 tag=tag %}">First</a>
            {% else %}
            <a href="{% url view page=1 %}">First</a>
            {% endif %}
        {% endif %}
        {% if list.has_previous and list.number != 2 %}
            {% if tag %}
            <a href="{% url view page=list.previous_page_number tag=tag %}">Previous</a>
            {% else %}
            <a href="{% url view page=list.previous_page_number %}">Previous</a>
            {% endif %}
        {% endif %}
        {% for i in posts.paginator.page_range %}
            {% if tag %}
            {% if list.number != i %}<a href="{% url view page=i tag=tag %}">{% endif %}{{ i }}{% if list.number != i %}</a>{% endif %}
            {% else %}
            {% if list.number != i %}<a href="{% url view page=i %}">{% endif %}{{ i }}{% if list.number != i %}</a>{% endif %}
            {% endif %}
        {% endfor %}
        {% if list.has_next and list.number != list.paginator.num_pages|add:-1 %}
            {% if tag %}
            <a href="{% url view page=list.next_page_number tag=tag %}">Next</a>
            {% else %}
            <a href="{% url view page=list.next_page_number %}">Next</a>
            {% endif %}
        {% endif %}
        {% if list.number < list.paginator.num_pages %}
            {% if tag %}
            <a href="{% url view page=list.paginator.num_pages tag=tag %}">Last</a>
            {% else %}
            <a href="{% url view page=list.paginator.num_pages %}">Last</a>
            {% endif %}
        {% endif %}
    </div>
{% endif %}

gergelypolonkaiweb/templates/pinterest-26239.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="p:domain_verify" content="26239be43e25a4bf839494fd2f35443f" />
    <title></title>

</head>
<body lang="en" style="background-color:#f7f5f5;background:#f7f5f5 url('http://passets-ak.pinterest.com/images/paper.jpg') repeat;padding:0;margin:0;">
<table cellspacing="0" cellpadding="0" border="0" width="100%" background="http://passets-ak.pinterest.com/images/paper.jpg">
    <tr>
        <td id="wrapper" style="padding:20px 20px 40px;">
            <table id="content" cellspacing="0" cellpadding="0" border="0" align="center" width="620">
                <!-- begin Branding Header -->
                <tr>
                    <td id="logo" align="center" style="padding:20px 0 40px;">
                        <a href="http://www.pinterest.com/website/verify/" Title="Verify domain" style="border:none;">
                          <img src="http://passets-ak.pinterest.com/images/email/logo.gif" width="200" height="52" style="vertical-align:top;outline:none;border:none;" alt="Verify website" />
                        </a>
                    </td>
                </tr>
                <!-- end Branding Header -->
                <!-- begin Primary Section Header -->
                <tr>
                    <td class="header" background="http://passets-ec.pinterest.com/images/mail/double_rules620.gif" align="center">
                        <table cellspacing="0" cellpadding="0" border="0" align="center">
                            <tr>
                                <td background="http://passets-ak.pinterest.com/images/paper.jpg" style="background-color:#f7f5f5;">
                                    <h1 style="font-family:georgia,serif;font-weight:normal;font-size:22px;line-height:21px;color:#211922 !important;text-shadow:0 1px 0 #FFFFFF;margin:0;padding:0 20px;">


                                                Hi, Gergely!


                                    </h1>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <!-- end Primary Section Header -->



    <!-- begin Comment -->
    <tr>
        <td class="comment_wrap" style="padding:30px 0 30px 8px;">
            <table cellspacing="0" cellpadding="0" border="0">
                <tr>
                    <td width="1" style="background-color:#eceaeb"></td>
                    <td class="" style="background-color:#FFFFFF;padding:0px;border-top:1px solid #eae9e9;border-bottom:1px solid #b2b1b1;border-left:1px solid #d4d2d3;border-right:1px solid #d4d2d3;">
                        <table cellspacing="0" cellpadding="0" border="0">
                            <tr>
                                <td>
                                    <table class="comment_container" cellspacing="0" cellpadding="0" border="0" width="617">
                                        <tr>





    <td class="profile_image" width="80" valign="top">
        <a href="http://www.pinterest.com/website/verify/" title="Gergely Polonkai">
            <img src="http://passets-ec.pinterest.com/images/NoProfileImage.png" width="80" height="80" style="vertical-align:top;outline:none;border:none;" alt="Gergely Polonkai" />
        </a>
    </td>



        <td class="comment_text" width="341">
            <p style="font-family:'helvetica neue',helvetica,arial,sans-serif;font-size:14px;color:#211922;line-height:20px;text-shadow:0 1px 0 #FFFFFF;margin:0;padding:5px 0 5px 15px;">Looking good! You are ready to return to the verification page and complete the process.</p>
        </td>




<td class="button_row" width="140" align="right" style="padding:20px;">
    <table class="button" cellspacing="0" cellpadding="0" border="0">
        <tr>
            <td class="button_text" height="34" align="center" background="http://passets-ak.pinterest.com/images/mail/button_borderless.gif" style="background-repeat:repeat-x;-moz-border-radius:6px;-webkit-border-radius:6px;-o-border-radius:6px;-ms-border-radius:6px;-khtml-border-radius:6px;border-radius:6px;background-position:top left;background-color:#d43638;border:1px solid #910101;white-space:nowrap;height:34px;">
                <a href="http://www.pinterest.com/website/verify/" style="color:#fcf9f9;cursor:pointer;text-align:center;text-decoration:none;vertical-align:baseline;" title="Go To Board">
                    <!--[if gte mso 9]>&nbsp;&nbsp;<![endif]-->
                    <span style="padding:9px 15px;color:#fcf9f9;text-decoration:none;color:#fcf9f9;font-family:'helvetica neue',helvetica,arial,sans-serif;font-weight:bold;font-size:18px;line-height:18px;text-shadow:0 -1px #933640;white-space:nowrap;">Go To Pinterest</span>
                    <!--[if gte mso 9]>&nbsp;&nbsp;<![endif]-->
                </a>
            </td>
        </tr>
    </table>
</td>



                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td width="1" style="background-color:#eceaeb"></td>
                </tr>
                <tr>
                    <td width="1" style="background-color:#eceaeb"></td>
                    <td height="1" style="background-color:#d5d3d4"></td>
                    <td width="1" style="background-color:#eceaeb"></td>
                </tr>
                <tr>
                    <td width="1"></td>
                    <td height="1" style="background-color:#e8e6e7"></td>
                    <td width="1"></td>
                </tr>
            </table>
        </td>
    </tr>
    <!-- end Comment -->




                <tr>
                    <td align="center" style="padding:10px 0 30px;">

                        <h4 style="font-family:georgia,serif;font-weight:normal;font-size:21px;color:#211922 !important;text-shadow:0 1px 0 #FFFFFF;margin:0;padding:0;">Happy pinning!</h4>

                    </td>
                </tr>
                   <!-- begin Badge Rule -->
                <tr>
                    <td id="badge_rule" height="18" width="100%" background="http://passets-ec.pinterest.com/images/mail/badge_rule620.gif" align="center"></td>
                </tr>
                <!-- end Badge Rule -->
                <!-- begin Subscription Notification -->
                <tr>
                    <td align="center" style="padding:30px 0 15px;">
                    </td>
                </tr>
                <!-- end Subscription Notification -->
                <!-- begin Copyright and Legal -->
                <tr>
                    <td align="center">
                        <p style="font-family:'helvetica neue',helvetica,arial,sans-serif;font-size:10px;color:#999999;text-shadow:0 1px 0 #FFFFFF;line-height:1.35em;margin:0;padding:0;"><span class="symbolfix">&copy;</span>2014 Pinterest, Inc. <font style="color:#AAA;padding:0 2px;">|</font> All Rights Reserved<br/><a href="/about/privacy/" style="color:#999;text-decoration:underline;text-shadow:0 1px 0 #FFFFFF;">Privacy Policy</a> <font style="color:#AAA;padding:0 2px;"> |</font> <a href="/about/terms/" style="color:#999;text-decoration:underline;text-shadow:0 1px 0 #FFFFFF;">Terms and Conditions</a></p>
                    </td>
                </tr>
                <!-- end Copyright and Legal -->
            </table>
        </td>
    </tr>
</table>
</body>
</html>